import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export interface AttendanceLog {
  idno: string;
  name: string;
  dte_log: string;
  reason: string;
  terminal_id: string;
}

export interface ReportOptions {
  startDate: string;
  endDate: string;
  terminalId?: string;
}

export async function generateAttendancePDF(data: AttendanceLog[], options: ReportOptions): Promise<ArrayBuffer> {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(0, 0, 128); // Navy blue
  doc.text('infoLib Attendance Report', 105, 20, { align: 'center' });

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Period: ${options.startDate} to ${options.endDate}`, 105, 30, { align: 'center' });
  
  if (options.terminalId) {
    doc.text(`Terminal: ${options.terminalId}`, 105, 37, { align: 'center' });
  }

  // Stats Summary
  const uniqueStudents = new Set(data.map(d => d.idno)).size;
  
  doc.setDrawColor(200);
  doc.line(20, 45, 190, 45);
  
  doc.setFontSize(10);
  doc.setTextColor(0);
  doc.text(`Total Records: ${data.length}`, 20, 52);
  doc.text(`Unique Students: ${uniqueStudents}`, 80, 52);
  doc.text(`Generated at: ${format(new Date(), 'yyyy-MM-dd HH:mm')}`, 140, 52);

  // Table
  const tableData = data.map(log => [
    format(new Date(log.dte_log), 'yyyy-MM-dd HH:mm'),
    log.idno,
    log.name,
    log.course,
    log.reason,
    log.terminal_id
  ]);

  autoTable(doc, {
    startY: 60,
    head: [['Date/Time', 'ID No', 'Student Name', 'Course', 'Reason', 'Terminal']],
    body: tableData,
    headStyles: { fillColor: [0, 0, 128], textColor: 255 },
    alternateRowStyles: { fillColor: [240, 240, 240] },
    margin: { top: 60 },
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount} - Generated by infoLib v1.0`,
      105,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  return doc.output('arraybuffer');
}
